### PR TITLE
appman.xml: update to Haxe 3.2.0

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by elsassph** [comment]
I think we should offer both 3.1.3 and 3.2 downloads for now.

**Comment by Gama11** [comment]
Ok. They need a different `Id` I guess? Does it matter what those are? `haxe3setup1` and `haxe3setup2` would work?

**Comment by Meychi** [comment]
Nope, but haxe3setup2 is better.

**Comment by Gama11** [comment]
Updated.

**Pull request merged**
