### PR TITLE
 [ProjectManager] PropertiesDialog theming fixes...

### PR DESCRIPTION
**Pull request by SlavaRa**
Before fix:
before
After:
after

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Meychi please check this pr

**Comment by Meychi** [comment]
This is not correct, layout breaks as seen on your after image, i think you only need to set font.

**Comment by SlavaRa** [comment]
Oh.. ok

**Comment by SlavaRa** [comment]
@Meychi fixed

**Comment by Neverbirth** [comment]
Merged, but note that one line has wrong formatting... I will fix it.

**Comment by SlavaRa** [comment]
>Merged, but note that one line has wrong formatting...
Sorry 👍

**Pull request merged**
