### PR TITLE
Support of AIR 24 and FlashPlayer 24. closes issue #1418

### PR DESCRIPTION
**Pull request by SlavaRa**
@Meychi please update http://www.flashdevelop.org/appman/frameworks_flexsdk_9-22.zip to 24 version

### CODE REVIEW

**Comment by Meychi** [comment]
I will do that over the weekend and merge.

**Comment by SlavaRa** [comment]
Thanks ;)

**Comment by Meychi** [comment]
Done. Could you also update the links from "frameworks_flexsdk_9-22.zip" to "frameworks_flexsdk_9-24.zip" in appman.xml?

**Comment by SlavaRa** [comment]
Done.

**Pull request merged**
