### PR TITLE
Result grouping

### PR DESCRIPTION
**Pull request by chipshort**
Allows to group the items in the ResultsPanel by other columns than file.

screenshot1
screenshot2
screenshot3

### CODE REVIEW

**Comment by SlavaRa** [comment]
Looks like good, but please use int instead of Int32(you have Int32 and int)

**Comment by Neverbirth** [comment]
The PR is still missing a thing plus there is a couple of details to fix.

**Comment by chipshort** [comment]
I just changed the behaviour to show no grouping if you click the column for the third time. Instead everything is shown in the order it showed up in the output:

nogrouping

**Comment by Neverbirth** [comment]
This last change should fix #1463.

**Pull request merged**
