### PR TITLE
Fix "The FixedSizeQueue has zero capacity" Error

### LINKED ISSUE #1612: The FixedSizeQueue has zero capacity.
```
System.InvalidOperationException: The FixedSizeQueue has zero capacity.
   at PluginCore.Collections.FixedSizeQueue`1.Enqueue(T item)
   at FlashDevelop.Managers.ClipboardManager.HandleWndProc(Message& m)
   at FlashDevelop.MainForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
@wise0704 5.2.172 development

### PR DESCRIPTION
**Pull request by wise0704**
Closes #1612

### CODE REVIEW

**Comment by SlavaRa** [comment]
Maybe it's worth do it in the settings?

**Comment by wise0704** [comment]
It already is:
https://github.com/fdorg/flashdevelop/blob/development/FlashDevelop/Settings/Accessors.cs#L368

**Comment by SlavaRa** [comment]
I mean https://github.com/fdorg/flashdevelop/blob/development/FlashDevelop/Settings/Accessors.cs#L353

**Comment by SlavaRa** [comment]
Now the first commit does not make sense)

**Comment by wise0704** [comment]
Oops, I thought I put `--amend`.

**Pull request merged**
