### PR TITLE
Use FIPS 140-2 compliant algorithm if available when required

### PR DESCRIPTION
**Pull request by elsassph**
After installing Cisco VPN client, FlashDevelop stopped working because it's using non FIPS compliant  algorithms.

### CODE REVIEW

**Comment by Meychi** [comment]
???, AnyConnect?

**Comment by elsassph** [comment]
Yes, Cisco AnyConnect. It will only work with FIPS enabled.
Maybe the change is due to Win10 Insider Preview, but FD basically doesn't work without this fix.

**Comment by Meychi** [comment]
Seems its a local policy setting in AnyConnect and it will "break" other apps also:

http://www.cisco.com/c/en/us/td/docs/security/vpn_client/anyconnect/anyconnect30/administration/guide/anyconnectadmin30/ac08localpolicy.html

**Comment by Meychi** [comment]
I don't have any issues but i have the setting off.

**Comment by elsassph** [comment]
I don't have the problem at work (Win10 Pro regular) but at home (Win10 Insider Preview) AnyConnect won't work without the FIPS flag set and it kills FD/HD.
My change is backward compatible as it defaults to using the regular managed encryption classes.

**Comment by elsassph** [comment]
(as a side note, everything on the computer is slower with the flag set)

**Pull request merged**
