### PR TITLE
[ASComplete] Fixed autocompletion after space within method. #fixes 1888

### PR DESCRIPTION
**Pull request by SlavaRa**
Now 'import completion', 'declaration completion' and 'override completion' disabled within method.

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Yanrishatum please test it

**Comment by SlavaRa** [comment]
I will write tests in next week

**Comment by Neverbirth** [comment]
I guess this is for #1887.

**Comment by Yanrishatum** [comment]
Tested, confirmed fixed.

**Pull request merged**
