### PR TITLE
[SourceControl] When file was added and is moved, remove old file from index

### PR DESCRIPTION
**Pull request by chipshort**
As requested in #1812

### CODE REVIEW

**Comment by SlavaRa** [comment]
looks like good

**Comment by gene-pavlovsky** [comment]
I tested the PR and while it improves the behavior, the original issue is still not fully fixed.
I found two more issues while testing, and described all of them in a comment to the original issue. If desired, I can split them to separate issues.

**Comment by SlavaRa** [comment]
WIP

**Comment by SlavaRa** [comment]
via #3099

**Pull request closed without merging**
