### PR TITLE
Improve `Assign statement to local variable`

### PR DESCRIPTION
**Pull request by SlavaRa**
Added ASComepleteTests.GetExpression
[Haxe] Fixed generation of `Assign statement to local variable` for callback

@Neverbirth @elsassph please review this PR

### CODE REVIEW

**Comment by SlavaRa** [comment]
Guys?

**Comment by Neverbirth** [comment]
I was going to check it yesterday at night, but you kept pushing commits heh. I will try to take a look into it today night.

**Comment by SlavaRa** [comment]
Okay, then I'm not going to push until

**Comment by SlavaRa** [comment]
@Neverbirth  please look, I can not do anything further ((

**Comment by SlavaRa** [comment]
;(

**Comment by Neverbirth** [comment]
As discussed, there is part of this that I will probably change, so please, don't work extensively over it. I will do my best... sadly I'm overloaded.

**Pull request merged**
