### PR TITLE
[Haxe][HaxeComplete] Fixed auto completion errors when classpath folder structure contains spaces. fixes #1657

### LINKED ISSUE #1657: Auto completion errors when classpath folder structure contains spaces or -
We ran into compile problems when a folder structure contained spaces or - signs, this was easily solved by enclosing all compiler arguments with "'s, however, now I'm getting the same errors when triggering auto complete on anything:

> Running process: C:\Programs\HaxeDevelop\Tools\fdbuild\fdbuild.exe "C:\Folder\Folder with space\project.hxproj" -ipc someguid -version "3.4.0" -compiler "C:\Programs\HaxeToolkit\haxe" -notrace -library "C:\Programs\HaxeDevelop\Library" -cp "C:\Folder\Folder with space\Project\libraries"
> Building project
> haxe  -cp "C:\Folder\Folder with space\Project\libraries"
> Build succeeded

Building works, but if you then try to autocomplete something:

> Error: Could not process argument space/Project/libraries
> invalid character: /

I did some testing with an empty new project, but the problem seems to occur whenever I add any reference to the project (either a classpath or the global classpath) that contains a space or -, so it looks like the compiler calls made by the IDE are not enclosed using "'s causing these errors.

This is running HaxeDevelop 5.2.0.3 and Haxe 3.4.0

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by Neverbirth** [comment]
I hope I will have time to check this tonight... but not sure.

**Comment by SlavaRa** [comment]
@Neverbirth  ?

**Comment by Neverbirth** [comment]
Hope I can definitely check this tonight.

**Comment by Neverbirth** [comment]
While checking this I found another unsupported case... I will commit a PR tomorrow.

**Comment by SlavaRa** [comment]
Thanks. What unsupported case did you find?

**Comment by Neverbirth** [comment]
It's possible to use double quotes with initialization macros, like `--macro include("some.pack", true)`. Those ones need to be escaped (just replacing with \" for example works, it's also possible to escape by doubling the quotes), right now it makes sending wrong arguments. As I said, it's a different case

**Pull request merged**
