### PR TITLE
HaxeFlixel Demos added to appman

### PR DESCRIPTION
**Pull request by PeyTy**
https://github.com/HaxeFlixel/flixel/issues/1753#issuecomment-244669230
Package' archive is hosted on peyty.github.io
Any issues?

### CODE REVIEW

**Comment by Meychi** [comment]
The package seems good, it should either be hosted at our or HaxeFlixel's repo or website or you need to provide a MD5 checksum for the package. 

How do you manage updates from HaxeFlixel repo?

**Comment by PeyTy** [comment]
> How do you manage updates from HaxeFlixel repo?

Automated script in node.js executed on a folder with demos and generates a package folder. You zip it, rename to *.fdz and viola, upload somewhere (and update link in appman.xml). Pretty simple to do.

**Comment by Meychi** [comment]
@Gama11: Is this binary ok to you guys?

**Comment by Gama11** [comment]
Yeah, seems ok to me. :+1: 

Long-term we probably want to host this somewhere else of course.

**Comment by Meychi** [comment]
Ok, as this is not hosted by us or HaxeFlixel, we need a MD5 checksum for the binary.

**Comment by PeyTy** [comment]
Changed link to raw.github.com/commit/file, added checksum

**Pull request merged**
