### PR TITLE
Small fixes for linux build

### PR DESCRIPTION
**Pull request by SlavaRa**
This changes have no effect on Windows build, but allow you to build project on Linux
https://travis-ci.org/SlavaRa/flashdevelop/builds/113441341

### CODE REVIEW

**Comment by Meychi** [comment]
@Neverbirth, does the build commands seem ok to you?

**Comment by Neverbirth** [comment]
The commands for AnyCPU doesn't seem to be right? plus they are presented 3 times instead of 2.

**Comment by SlavaRa** [comment]
I need to fix something?

**Comment by Meychi** [comment]
@SlavaRa: This has conflicts atm.

**Comment by SlavaRa** [comment]
Fixed. 
Win build - ok
Linux build - ok (https://travis-ci.org/SlavaRa/flashdevelop/builds/115979482)

**Comment by SlavaRa** [comment]
development merge into "SlavaRa:feature/fixes_for_linux_build"
Windows build - ok.
Linux build - ok(https://travis-ci.org/SlavaRa/flashdevelop/builds/118703386).

**Comment by SlavaRa** [comment]
@Meychi @elsassph @Neverbirth guys, what about this PR?

**Comment by elsassph** [comment]
@Meychi please merge as it may affect CI.

**Comment by wise0704** [comment]
What happened to de_DE.resx and ko_KR.resx files? It seems like every line is modified for them. Possibly a modification of line end characters?

**Pull request closed without merging**
