### PR TITLE
[Haxe][CodeRefactor] Fixed "Organize Imports" removes implicit imports of types within modules. fixes #191

### LINKED ISSUE #191: [haxe] "Organize Imports" removes implicit imports of types within modules
Organize imports does not seem to account for the fact that importing a module will also import also the types within.

Example with two files:

Test.hx

``` haxe
package;

class Test
{

}

typedef TestTypedef = Void->Void;
```

test/Import.hx

``` haxe
package test;

import Test.TestTypedef;

class Import
{
    public function new(test:TestTypedef) 
    {

    }
}
```

---

The explicit import of `TestTypedef` is not removed when organizing imports - when you change it to only `import Test;` however, it is removed, even though it is required for compilation.

Interestingly enough, another import has to be added to `Import.hx` - otherwise the Organize Imports option is greyed out.

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by Meychi** [comment]
Could you get around OrganizeImports : global::CodeRefactor.Commands.OrganizeImports decl?

**Comment by SlavaRa** [comment]
?

**Comment by Meychi** [comment]
Some how remove it, @Neverbirth said its possible.

**Comment by SlavaRa** [comment]
```
using CodeRefactor.Commands.OrganizeImports;
HaxeOrganizeImports : OrganizeImports 
```
? 

What's wrong with the `global::CodeRefactor.Commands.OrganizeImports`?

**Comment by Meychi** [comment]
Not consistent i guess.

**Comment by SlavaRa** [comment]
I can do HaxeOrganizeImports if this will speed up the merge.

**Comment by Meychi** [comment]
Yep.

**Comment by SlavaRa** [comment]
Fixed

**Comment by SlavaRa** [comment]
@Meychi now ok?

**Pull request merged**
