### PR TITLE
[Haxe][ASGenerator] Improved callback code generation.

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Neverbirth please review and merge this PR

**Comment by SlavaRa** [comment]
@Neverbirth what about this PR?

**Comment by SlavaRa** [comment]
fixes #1580

**Comment by Neverbirth** [comment]
From what I see this doesn't work properly on cases like `Void->(Void->Void)`.

**Comment by SlavaRa** [comment]
I will check this

**Comment by SlavaRa** [comment]
@Neverbirth fixed

**Comment by Neverbirth** [comment]
I've noticed something that maybe would be interesting to improve:

```
	static function foo(v:Int->(Void->Void)->(Void->(Void->Int))):Void
	{
		
	}
```

Produces:

```
	static function test(parameter0:Int, parameter1:(Void->Void)):(Void->(Void->Int)) 
	{
		
	}
```

You could produce cleaner code by removing the extra parenthesis, like:

```
	static function test(parameter0:Int, parameter1:Void->Void):Void->(Void->Int) 
	{
		
	}
```

**Pull request merged**
