### PR TITLE
Adds `Goto Type Declaration`

### PR DESCRIPTION
**Pull request by SlavaRa**
gototypedeclaration

### CODE REVIEW

**Comment by SlavaRa** [comment]
@elsassph @Neverbirth @Meychi please review this PR

**Comment by Neverbirth** [comment]
I won't have time today or tomorrow, but will try to make a decission before the end of the week.

**Comment by SlavaRa** [comment]
@Neverbirth thanks

**Comment by Neverbirth** [comment]
Will check today.

**Comment by Neverbirth** [comment]
I merge, although I think the back from type declaration option should be changed to something a bit more generic and also enable it in the cases when going to a normal declaration.

**Pull request merged**
