### PR TITLE
Dialog for Move refactoring command

### PR DESCRIPTION
**Pull request by SlavaRa**
Result:
coderefactor_move
@Meychi @elsassph @Neverbirth , guys, please review this PR

### CODE REVIEW

**Comment by andrew-git** [comment]
Useful feature

**Comment by markknol** [comment]
Neat! Looks like a feature flashdevelop could implement by default.

**Comment by Meychi** [comment]
Looks great! I see few things that should get fixed:

* Remove unnecessarty resources files 
* Make sure the dialog applies correct default font
* Works correctly in HighDPI

**Comment by SlavaRa** [comment]
okay, i do it today)

**Comment by SlavaRa** [comment]
@Meychi fixed ;)

**Pull request merged**
