### PR TITLE
Apply theme to the Resources dialog

### LINKED ISSUE #1179: "Open resource" dialog - add theme support
The `Project > Open resource` dialog remains one of the few commonly-used features lacking theme support.
It would look better if it supported themes (e.g. `Type Explorer` does).

### PR DESCRIPTION
**Pull request by wise0704**
Closes #1179

### CODE REVIEW

**Comment by wise0704** [comment]
This is the same pattern I used for clipboard history dialog too.

**Comment by Meychi** [comment]
Could this be done to all basic dialogs at the same time?

**Comment by wise0704** [comment]
This pattern to all basic dialogs individually?
Or something like override `Form.OnShown` in `SmartForm` and handle it there?
One small problem to the latter is that form back colours and label&checkbox fore colours are not defined in the theme files, so I have to manually fetch `"MenuStrip.BackColor"` and `"MenuStrip.ForeColor"` as done in this PR, and loop through the child controls to apply them.

**Comment by Meychi** [comment]
Hmm, maybe we should add proper support for basic forms with SmartForm and define the missing colors to the themes. We can default to current functionality by adding a setting that enables global coloring. Also we need to remember to add handling for theme event when the theme gets applied.

Do you have time for this or should i jump on it?

**Comment by wise0704** [comment]
No I don't really have time...

**Comment by Meychi** [comment]
Ok, i will check this.

**Comment by Meychi** [comment]
See #1719

**Pull request closed without merging**
