### PR TITLE
Added DocumentationGenerator as ContextualGenerator. fixes #511. fixes #393

### LINKED ISSUE #393: Add option to not generate stars in comment blocks
http://www.flashdevelop.org/community/viewtopic.php?f=6&t=11939

### LINKED ISSUE #511: haxe javadoc fails to add paramaters when there is one or more anonymous structure
When creating javadoc style documentation on a function containing at least one anonymous structure as paramater, the automatic javadoc generation fails to create every parameters of the function.
for instance it creates:

``` haxe
    /**
     * 
     */
    public static function pouet( { x:Int, y:Int }, z:Int ) {

    }
```

instead of

``` haxe
    /**
     * 
     * @param   {x:Int, y:Int}
     * @param   z
     */
    public static function pouet({x:Int, y:Int}, z:Int ) {

    }
```

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by Neverbirth** [comment]
I will do my best to check this one today.

**Comment by Neverbirth** [comment]
Sadly due to work couldn't fully check this one yet :/. @elsassph if you are able to take a look then great, I will try to look during the weekend, if by Sunday evening is not checked let's just go on and merge.

**Comment by SlavaRa** [comment]
maybe after the release? why rush :)

**Comment by Meychi** [comment]
Lets merge this after release.

**Comment by SlavaRa** [comment]
@Neverbirth @elsassph Have you reviewed at this pr?

**Comment by Neverbirth** [comment]
Sadly I couldn't yet... but from my side it can be merged and checked later, I guess it's ok if afterwards we see something that should be changed.

**Pull request merged**
