### PR TITLE
[Flash] Add support of new API Vector.<T> 

### PR DESCRIPTION
**Pull request by SlavaRa**
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Vector.html#insertAt()
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Vector.html#removeAt()

### CODE REVIEW

**Comment by wise0704** [comment]
Probs under a new folder `FlashDevelop/Bin/Debug/Library/AS3/intrinsic/FP19`?

**Comment by SlavaRa** [comment]
Nope. Will not work.
But my decision we have discussed in slack

**Comment by wise0704** [comment]
Ah ok. I was just curious.
But do you know the reason why putting it in a new folder does not work?

**Comment by elsassph** [comment]
Yeah FP19 could possibly work, but I figured it was probably not worth the complication.

**Pull request merged**
