### PR TITLE
Added community themes to appman.xml

### PR DESCRIPTION
**Pull request by JoeRobich**
Added my Visual Studio and Vibrant Ink inspired themes to the appman. I've tested them locally and believe I have the packaging of the fdz correct.

### CODE REVIEW

**Comment by JoeRobich** [comment]
actually there is an issue with my packaging will update this shortly.

**Comment by JoeRobich** [comment]
Updated packages to deploy copies of the themes under the correct folder.

**Comment by Meychi** [comment]
Are the checksums correct after update?

**Comment by JoeRobich** [comment]
Yes. I double checked =)

**Pull request merged**
