### PR TITLE
Update appman.xml

### PR DESCRIPTION
**Pull request by CamWiseOwl**
Add WakaTime plugin to Appman.

### CODE REVIEW

**Comment by Meychi** [comment]
Thanks! Nice to see new people contributing :)

You should to change the FDZ's extraction path to $(BaseDir)/Plugins to it to work in standalone and normal mode correctly. UserAppDir should not be used directly.

I had some difficulties finding your plugin's ui and i suggest adding it under Tools or offer the setting object for the main setting ui as other plugins do.

**Comment by Neverbirth** [comment]
@CamWiseOwl  I think you missed @Meychi comment?

**Comment by CamWiseOwl** [comment]
I could've sworn I wrote a comment other day.

@Neverbirth sort of, I've been bogged down with real life / job type stuff, sorry.
@Meychi Originally it did use BaseDir, then I read contributing before I PR'd and changed it to UserAppDir, it's now back to BaseDir.

UI was in the Help menu, moved that to Tools.
The external config file is part of WakaTime itself, used by the CLI and other WakaTime plugins.

**Comment by Meychi** [comment]
@CamWiseOwl, I changed the description in the contribution docs for this reason. :) I think its better to have it in tools. Ah ok.

**Pull request merged**
