### PR TITLE
[CI][Tests] Haxe 3.4.3 -> 3.4.6 (first try).

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@andyli please check it :)

**Comment by andyli** [comment]
I have never looked into the FD repo so the log is hard for me to read. It would be great if you can quote the relevant part for me next time.

```
1) Test Error : ASCompletion.Completion.ASCompleteTests+Haxe.('s':String).
   System.NullReferenceException : Object reference not set to an instance of an object.
   at ASCompletion.Model.ClassModel.ClassDeclaration(ClassModel ofClass, Boolean qualified)
   at ASCompletion.Model.ClassModel.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.IO.TextWriter.Write(String format, Object arg0)
   at NUnit.Framework.TextMessageWriter.WriteValue(Object val)
   at NUnit.Framework.TextMessageWriter.WriteExpectedValue(Object expected)
   at NUnit.Framework.TextMessageWriter.WriteExpectedLine(Object expected, Tolerance tolerance)
   at NUnit.Framework.TextMessageWriter.DisplayDifferences(Object expected, Object actual, Tolerance tolerance)
   at NUnit.Framework.Constraints.EqualConstraint.DisplayDifferences(MessageWriter writer, Object expected, Object actual, Int32 depth)
   at NUnit.Framework.Constraints.EqualConstraint.WriteMessageTo(MessageWriter writer)
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
```
The errors were likely caused by https://github.com/HaxeFoundation/haxe/commit/91b8655c0af4adcec266146105c9b6b15a2f87f6
@RealyUniqueName I think you have to look into this.


Other than that, I noticed there were some errors related to Windows update:
```
Failures
 - kb2999226 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB2999226\tools\chocolateyinstall.ps1'.
 See log for details.
 - kb2919442 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB2919442\tools\ChocolateyInstall.ps1'.
 See log for details.
 - kb3035131 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
 See log for details.
```
These were "caused" by neko 2.2.0 being built with newer visual studio thus requiring some dll files, which need those windows updates. Installing those updates requires the Windows update service. To enable the service, run `Set-Service wuauserv -StartupType Manual` in powershell ([like so](https://github.com/andyli/HaxeCI/blob/d03d893f42f3ecdfd72e4db0e5ba8958c332213f/appveyor.yml#L9)).
I'm confused that these errors were also found in the master branch's builds but they passed: https://ci.appveyor.com/project/FlashDevelop/flashdevelop-devel/build/5.3.1.134, but I still believe it is better to be fixed anyway.

**Comment by SlavaRa** [comment]
Sorry
```
Installed:
 - kb2919355 v1.0.20160915
 - kb3033929 v1.0.3
 - neko v2.2.0
 - haxe v3.4.6
 - vcredist2017 v14.12.25810
 - vcredist140 v14.12.25810
 - chocolatey-windowsupdate.extension v1.0.2
Failures
 - kb2999226 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB2999226\tools\chocolateyinstall.ps1'.
 See log for details.
 - kb2919442 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB2919442\tools\ChocolateyInstall.ps1'.
 See log for details.
 - kb3035131 (exited 1058) - Error while running 'C:\ProgramData\chocolatey\lib\KB3035131\Tools\ChocolateyInstall.ps1'.
 See log for details.
Refreshing environment variables from the registry for powershell.exe. Please wait...
Finished
```

**Comment by andyli** [comment]
Yes, see my comment above for the fix. ;)

**Comment by RealyUniqueName** [comment]
> The errors were likely caused by HaxeFoundation/haxe@91b8655
> @RealyUniqueName I think you have to look into this.

Sorry, I'm not familiar with FD source and I don't understand how my change could affect this. That change should only affect as3 generator of the haxe compiler and only classes with "Object" name.

**Pull request closed without merging**
