### PR TITLE
Fixes generate static variable and static function

### PR DESCRIPTION
**Pull request by SlavaRa**
BUG in release 5.1.1, code for example:
```
package {
	public class Main {
		public function Main() {
			Main.test|;
		}
	}
}
```
result after generating variable:
```
package {
	public class Main {
		private var test;//must be private static var test;
		public function Main() {
			Main.test;
		}
	}
}
```

BUG in developmnet version if setting generate explicit scope is true, code for example:
```
package;
public class Main {
	public static function main() {
		test|;
	}
}
```
result after generating variable:
```
package;
public class Main {
	static private var test;
	public static function main() {
		this.test;//must be Main.test
	}
}
```

### CODE REVIEW

**Comment by SlavaRa** [comment]
@elsassph @Neverbirth please review this PR.

**Comment by Neverbirth** [comment]
There doesn't seem to be unit tests taking into account the explicit scope case, aren't they? They could be added, what do you think?

**Comment by SlavaRa** [comment]
I doubt that I understood correctly your 1st comment(( You could say, in more detail, what should I do?

**Comment by Neverbirth** [comment]
I mean that you could make tests where you set the explicit scope setting to true, and then validate that everything is working correctly. I hope I explained myself better this time.

I don't think it's mandatory in order to approve the PR, but if you can do it it will be nice to have more coverture of the code.

**Comment by SlavaRa** [comment]
Now I understand, thank you, I will refactor soon

**Comment by SlavaRa** [comment]
I'll reopen this PR tonight

**Pull request closed without merging**
