### PR TITLE
[Haxe][ASGenerator] Fixed typing by short type after `assign statement to var`. fixes #1704

### LINKED ISSUE #1704: [Haxe] Wrong result after assign statement to var
```haxe
package;

class Main {
	static function main() {
		new Foo().foo(); |
	}
}

class Foo extends Sprite {
	public function new() {}
	public function foo():haxe.ds.Vector<haxe.Timer> return null;
}
```

expected result:
```haxe
package;
import haxe.Timer;
import haxe.ds.Vector;

class Main {
	static function main() {
		var foo:Vector<Timer> = new Foo().foo()
	}
}

class Foo extends Sprite {
	public function new() {}
	public function foo():haxe.ds.Vector<haxe.Timer> return null;
}
```

actual result:
```haxe
package;
import haxe.Timer;

class Main {
	static function main() {
		var foo:Timer> = new Foo().foo()
	}
}

class Foo extends Sprite {
	public function new() {}
	public function foo():haxe.ds.Vector<haxe.Timer> return null;
}
```

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
Depends on #1706

**Comment by Neverbirth** [comment]
I think you created this PR from #1706? It conflicts.

**Comment by Neverbirth** [comment]
?

**Comment by SlavaRa** [comment]
It's strange. I will check all the cases today after work

**Pull request merged**
