### PR TITLE
Added shortcut "Start new line below current line" (Shift + Enter)

### PR DESCRIPTION
**Pull request by SlavaRa**
shift_plus_enter_start_new_line_below_current_line

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Meychi please review this PR

**Comment by Meychi** [comment]
Also instead of resending the event, you could listen the Key event in low priority and handle it if its not handled yet. Comments: @Neverbirth?

**Comment by SlavaRa** [comment]
Only for this Shortcut?

**Comment by Meychi** [comment]
Maybe its fine as is if @Neverbirth thinks it ok.

**Comment by wise0704** [comment]
oh no another hardcoded shortcut...

**Pull request closed without merging**
