### PR TITLE
Fixed behavior after click of on the target build selector

### PR DESCRIPTION
**Pull request by SlavaRa**
Click of on "target build selector" before fix:
bug_click_on_targetbuildselector

Click after fix:
fixes_click_ob_targetbuildselector

### CODE REVIEW

**Comment by Gama11** [comment]
I think that behavior is intentional so you can use unlisted targets.

**Comment by SlavaRa** [comment]
For this is the configuration file

**Comment by elsassph** [comment]
This is intentional.

**Comment by SlavaRa** [comment]
ok.

**Pull request closed without merging**
