### PR TITLE
Better package and class name check

### PR DESCRIPTION
**Pull request by Neverbirth**
Modified the package and class name validation to be more aggressive. Fixes issue #894 and some others I've found while testing.

I've also seen that the code tries to display the messagebar with two lines of text, but only one is displayed, but haven't looked into this.

### CODE REVIEW

**Comment by Neverbirth** [comment]
I'm sure AS2 package replacement is broken, I'll check it today.

**Comment by elsassph** [comment]
What's the state of this PR?

**Comment by Neverbirth** [comment]
After working on this I think I have discovered a bug in another part of FD, but still didn't check it nor the AS2 case.

**Comment by Meychi** [comment]
?

**Comment by Neverbirth** [comment]
I haven't looked into this yet, I've been busy with more important tasks, then I plan to come back to this, as I think it's also important.

**Pull request closed without merging**
