### PR TITLE
support `--cwd` in hxml projects

### LINKED ISSUE #2051: --cwd in hxml is not supported in haxe hxml projects
I've created hxml that looks like this:

    --cwd ..\build\html5
    --macro addGlobalMetadata('', '@:expose')
    project-html5.hxml

It compiles fine, but flashdevelop fails to determine classpaths from it and thus does not show my source files in Project pane.

PS I changed the title. The actual problem is not in sub-hxmls, but in --cwd compiler option.

### PR DESCRIPTION
**Pull request by romamik**
This should fix https://github.com/fdorg/flashdevelop/issues/2051
This is my first code in C# for very long time. Also I did not manage to properly test this. But I've opened my project and it worked.

### CODE REVIEW

**Comment by SlavaRa** [comment]
it is fixed in #1827

**Comment by romamik** [comment]
@SlavaRa I briefly looked at your pull-request. Are you sure it adds support for `--cwd`? Support for sub-hxmls is already there in actual release, but that's not enough.

What are the chances your PR will be merged? It's quite old... 

offtopic: can I just replace compiled binaries in my installation of flashdevelop? I would like to switch to version with that fixed...

**Comment by romamik** [comment]
@SlavaRa I've tested your pull request, and it does not solve my issue.

I've created small test project. FlashDevelop project is in `folder2` folder.
[fdTestHxml.zip](https://github.com/fdorg/flashdevelop/files/1774649/fdTestHxml.zip)

This is how it looks with your pull request
image

And this is how it looks with mine:
image

PS Also I've noticed that `.hxml` file should be in same directory as flashdevelop project. That also should be fixed IMHO, but this looks like seperate issue

**Comment by SlavaRa** [comment]
Ok, thanks, I'll review this PR tomorrow.

**Pull request merged**
