### PR TITLE
[UnitTests][ASGeneratorTests] Remove duplicated code

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Neverbirth ?

**Comment by Neverbirth** [comment]
I don't know about others' opinion on the subject. Personally I don't like that the common function used for some of the cases does more than needed, hiding possibly some interesting information for future use.

If @Meychi is ok with it it can be merged.

**Comment by SlavaRa** [comment]
This code is simply duplicated everywhere and when you need to add something you have to add it everywhere, everywhere the same thing

**Comment by elsassph** [comment]
Less boilerplate sound good.

**Comment by Neverbirth** [comment]
OK.

**Pull request merged**
