### PR TITLE
Fixed fails after renaming when renaming function parameters in some cases. part1 #467

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@elsassph @Neverbirth please review this PR

**Comment by Neverbirth** [comment]
Is it really needed to use FRSearch in this case? cannot we check the local vars of the function and the existing members in the class hierarchy?

**Comment by SlavaRa** [comment]
I got rid of `FRSearch`, I wanted to do PR in the evening)

**Comment by Neverbirth** [comment]
Not a problem at all.

**Pull request merged**
