### PR TITLE
[ASGenerator][Bug] Disabled `Assign statement to variable` for `some()` where `some` is `function some():Void`. fixes #1757

### LINKED ISSUE #1757: [ASGenerator][Bug] Disable contextual codegenerator for `some()` where `some` is `function some():Void`
```haxe
...
some(); | // | <-- cursor, Assign statement to variable
...
function some():Void {}
```

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Neverbirth please review this PR

**Comment by Neverbirth** [comment]
Should I expect some unit test?

**Comment by SlavaRa** [comment]
I have not yet figured out how to make them :(

**Comment by SlavaRa** [comment]
@Neverbirth  Do we have something like that?

**Comment by Neverbirth** [comment]
I didn't look into it, but I'm sure it should be somehow possible, even if maybe not the best. Merging for now... maybe we can look into it together some other day... these latest days are really difficult.

**Comment by SlavaRa** [comment]
@Neverbirth Thanks, I'll think about how to organize tests :)

**Pull request merged**
