### PR TITLE
Add Images for Organise & Truncate Imports refactor menu

### PR DESCRIPTION
**Pull request by wise0704**
image

Plus just some minor code cleanup.

### CODE REVIEW

**Comment by Neverbirth** [comment]
@Meychi up to you this one. I don't specially care about this heh.

**Comment by Meychi** [comment]
Hmm... me either, @wise0704 whats the reasoning for this? As in VS?

**Comment by wise0704** [comment]
Not really from VS, but it had been in my plan to add meaningful icons for some contextual refactor menu when I added those refactoring menus. I think it makes it look even more fancy. 

Imports are for packages, so I tried to find package icons before when I first added the refactor menus, but couldn't figure out where the icons were then haha. Organise&truncate packages are kind of separated from the rest of the menus.

**Comment by Neverbirth** [comment]
For organize maybe there are more meaningful icons like the typical sort icon with A->Z inside or similar.

**Comment by wise0704** [comment]
How about this?
image

**Comment by Neverbirth** [comment]
Looks definitely better.

**Pull request merged**
