### PR TITLE
Fixes issue #1459

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by Neverbirth** [comment]
Personally I would prefer some property of ContextFeatures, as we have for other stuff like dot, hasGenerics, etc, etc. I don't know what others like @elsassph thinks.

**Comment by SlavaRa** [comment]
Well, I'll try to do otherwise

**Comment by SlavaRa** [comment]
I think we could add a list of postfix operators to ContextFeatures. @Neverbirth what do you think about that?

**Comment by Neverbirth** [comment]
I would be ok with it.

**Pull request closed without merging**
