### PR TITLE
Toolbar dropdown size

### PR DESCRIPTION
**Pull request by elsassph**
Made target selector a bit larger by default, and now both drop downs have a configurable size.

### CODE REVIEW

**Comment by Neverbirth** [comment]
Why not just make the dropdown to adjust to the max size? You can always set a minimum size and/or padding.

**Comment by elsassph** [comment]
Good point - not sure how to do it though.

**Comment by elsassph** [comment]
I'd still prefer a wider fixed width thing in fact.

**Comment by Neverbirth** [comment]
There are several ways to do that, for example:

https://github.com/Neverbirth/flashdevelop/blob/build_configs/External/Plugins/ProjectManager/Controls/FDMenus.cs#L201

**Comment by elsassph** [comment]
Ok, but if we do that you'll need to introduce min and max combo widths.

**Comment by Meychi** [comment]
Lets just make it little bigger without any settings, ok?

**Comment by elsassph** [comment]
@Meychi that was my idea - and for those wanting control there's a theme value that can be changed.

**Comment by gene-pavlovsky** [comment]
Hey guys, off topic here! I only program in AS3 and have never seen the Target combo contain any options. Where is it actually used? Or is it possible to add custom targets by myself? At the moment I do it with ant, e.g. my build.xml has android, ios, desktop and web targets for my app. But maybe if I can see those in the target dropdown, would be nice?

**Comment by elsassph** [comment]
The list has default items for some specific project types. Any value you type here will be available as an argument in commands: $(TargetBuild).

**Comment by gene-pavlovsky** [comment]
@elsassph Thanks; since it's a drop-down, I didn't figure I could just type something in there. This raises a bunch more questions, I opened #1181 to discuss this.

**Pull request merged**
