### PR TITLE
Neko template run.bat

### PR DESCRIPTION
**Pull request by markknol**
Only pause on errors. Otherwise you have a lot cmd tabs open after some runs.

### CODE REVIEW

**Comment by elsassph** [comment]
Well the point is that you can read your output.

Clever suggestion though, maybe you could define some "set PAUSE_ON_ERRORS" option in the script?

**Comment by Meychi** [comment]
@elsassph: Merge or close?

**Comment by elsassph** [comment]
I'd merge if it'd be based on having a `PAUSE_ON_ERRORS` flag controlling the behaviour.

**Comment by Meychi** [comment]
Ok, @markknol?

**Comment by Meychi** [comment]
@markknol, seems you pushed you changes to the wrong branch :)

**Comment by markknol** [comment]
I put it here: 
https://github.com/markknol/flashdevelop/blob/patch-1/FlashDevelop/Bin/Debug/Projects/340%20Haxe%20-%20Neko%20Project/Run.bat.template
Take it if you like it.

GIT; Sometimes I have no idea what i'm doing. :confused:

**Comment by Meychi** [comment]
Hmm... the file only adds the PAUSE_ON_ERRORS flag without that first mode, is that correct?

**Comment by markknol** [comment]
Ill close this since I have no idea what to do with it hehe.

**Pull request closed without merging**
