### PR TITLE
Support of shortcuts "To Lowercase", "To Uppercase" for "Find and Replace" dialogs

### PR DESCRIPTION
**Pull request by SlavaRa**
@Meychi @elsassph @Neverbirth please review this PR and merge if all ok.

### CODE REVIEW

**Comment by Neverbirth** [comment]
Personally I don't see this as something that would really improve UX or productivity, but I left the other guys to decide. What I don't like is the use of var for things like int.

**Comment by SlavaRa** [comment]
Now I have to work with a large number of ported code from c# to haxe. One of the tasks is to rename the constants. I have to translate their names to upper case by hand and it takes a long time, so I decided to add hotkeys.
About var for int, I think that the style should be one for the string and int and so on

**Comment by Neverbirth** [comment]
I don't really get your last sentence.

**Comment by SlavaRa** [comment]
instead of
```csharp
int pos = 1;
var str = "string";
```
just
```csharp
var pos = 1;
var str = "string";
```
I think that the style of writing should not depend on the type of a variable.

**Comment by Neverbirth** [comment]
Oh, well, then I guess we don't agree on it, I don't think type inference is an all or nothing case. Anyway, in this case I would write both int and string.

**Comment by SlavaRa** [comment]
In this case the type is obvious when initializing.
Or we should opt out of the use of "var" for all.

**Pull request closed without merging**
