### PR TITLE
Added Haxe/C# template

### PR DESCRIPTION
**Pull request by markknol**
It's missing the _project.png_ file.

### CODE REVIEW

**Comment by Meychi** [comment]
I think the template should be consistent the AS3/Flex Mobile templates we have. Same naming and bat files under bat dir. What do you think?

**Comment by markknol** [comment]
What naming is exactly different or how should it be? I used the template files based on the Haxe/Neko template.

**Comment by elsassph** [comment]
The templates should include hints on how to load .NET DLLs (custom and STD). I'll try to share something.

**Comment by markknol** [comment]
I've added the project image and changed the batch files

**Pull request closed without merging**
