### PR TITLE
Update to .NET 4

### PR DESCRIPTION
**Pull request by Neverbirth**

### CODE REVIEW

**Comment by wise0704** [comment]
Did you make sure that no code needs to be updated?
[.NET Framework 4 Migration Issues](https://msdn.microsoft.com/library/ee941656(v=vs.100).aspx)
[Obsolete Types in the .NET Framework 4](https://msdn.microsoft.com/en-us/library/ee461503(v=VS.100).aspx)
[Obsolete Members in the .NET Framework 4](https://msdn.microsoft.com/en-us/library/ee471421(v=VS.100).aspx)

Also, what's the reason to choose 4.0 instead of 4.5+?
[.NET Framework Versions and Dependencies](https://msdn.microsoft.com/en-us/library/bb822049(v=vs.110).aspx)
Up to 4.6 Vista is supported.

**Comment by SlavaRa** [comment]
A very good idea

**Comment by wise0704** [comment]
Note: this closes #1595

**Comment by SlavaRa** [comment]
@Meychi What do you think about this PR?

**Comment by Neverbirth** [comment]
I will merge this...

**Pull request merged**
