### PR TITLE
Copy Tree command and combine inherited (#4)

### PR DESCRIPTION
**Pull request by hgupta9**
@Neverbirth : All your points have been taken into consideration, static settings bool's have been added for each change in behavior, and the original behavior has been restored by default. Dictionary has been freed at end of CopyTree. String issues have been fixed using full classpaths. 

@Meychi : I didn't create an issue yet, because I corrected every issue brought up. And yes, I rewrote and re-tested everything with the code from `fd5` branch.

1. Add "Copy Tree", "Copy Value" "Copy ID" commands to `DataTreeControl`
2. Add the following setting bools to `DataTreeControl`
  - CopyTreeMaxChars - default : 1000000
  - CopyTreeMaxRecursion  - default : 10
  - CombineInherited - default : false
  - ShowStaticInObjects - default : true
  - ShowFullClasspaths - default : true
  - ShowObjectIDs - default : true
3. Add string utils (`StringsHelper`)
4. Add getters in `ValueNode` for:
  - IsPrimitive
  - ClassPath
  - ID
5. Arrays show as "Array" instead of "[]"
6. Vectors show as "Vector.<*>" instead of "AS3.vec.Vector.<*>"
7. Add the following optional features to the debug data tree
  - Hide object IDs ("@abc123")
  - Hide full class paths ("flash.display.MovieClip" shows as "MovieClip")
  - List inherited vars alongside main vars of a class instance
  - `[static]` does not show in dynamic objects

**Preview**
This is what it looks like by default. No major changes compared to FD4.

fd_copyastree_v4

### CODE REVIEW

**Comment by Neverbirth** [comment]
Will look into this later today. Really sorry for the delay.

**Comment by hgupta9** [comment]
@Neverbirth, @elsassph, @Meychi - Can you guys check this and commit it or give me feedback?

**Comment by Neverbirth** [comment]
The reviewing was done, the PR will be merged although with some slight modifications and adjustments (together with localization and settings). Thanks for the contribution!

**Comment by hgupta9** [comment]
That is totally cool. Thank you all for your suggestions!

**Comment by hgupta9** [comment]
@Neverbirth 
Any idea what are the modifications and adjustments? (apart from localization and settings)

**Comment by hgupta9** [comment]
@Meychi - Can you merge this? Its perfectly working ..

**Comment by Meychi** [comment]
This PR was assigned to @Neverbirth, he has been busy lately but promised to finish this soon.

**Comment by Meychi** [comment]
Done.

**Comment by hgupta9** [comment]
@Meychi - Why cannot I see my code in fd5 branch as yet? It appears my changes have not yet been merged into FD repo??

https://github.com/fdorg/flashdevelop/blob/fd5/External/Plugins/FlashDebugger/Controls/DataTree/ValueNode.cs

https://github.com/fdorg/flashdevelop/blob/fd5/External/Plugins/FlashDebugger/Controls/DataTreeControl.cs

**Comment by hgupta9** [comment]
@Neverbirth - Which branch did you merge the code into?

**Comment by Neverbirth** [comment]
Since FD 4.7 was considered "finished" the development branch moved back from fd5 to development

https://github.com/fdorg/flashdevelop/commits/development?author=hgupta9

**Comment by hgupta9** [comment]
@Neverbirth - Thank you!! I'll consider contributing more code soon.

**Pull request closed without merging**
