### PR TITLE
[ASCompletion] Added "ASCompletion.DotCompletion" DataEvent

### PR DESCRIPTION
**Pull request by SlavaRa**
This event is necessary for plugins like postfix-autocompletion and the like

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Neverbirth please review this PR

**Comment by SlavaRa** [comment]
@Neverbirth what do you think about it?

**Comment by Neverbirth** [comment]
I will ping you tomorrow on Slack, there is an alternative that maybe is better.

**Comment by SlavaRa** [comment]
@Neverbirth  ?

**Comment by SlavaRa** [comment]
Bump

**Comment by SlavaRa** [comment]
Wow, Thanks!

**Pull request merged**
