### PR TITLE
Show more path if several same-named references exists

### PR DESCRIPTION
**Pull request by yar3333**
project

### CODE REVIEW

**Comment by SlavaRa** [comment]
nice )

**Comment by elsassph** [comment]
Nice, but could we just add 'library' to the tokens ignored (like 'src')? That is using the mechanism which already exists.

**Comment by yar3333** [comment]
@elsassph: May be yes, how to do that ("library" is duplicated only in my projects - it is not a common practice; other developers can have other duplicated names)?

**Comment by elsassph** [comment]
Well 'library' seen a fairly generic term, like 'src' so it would be also be worth not counting as a useful folder name.
Your solution is somehow smarter but it works only if you have two projects using 'library' as the last folder name.

**Comment by yar3333** [comment]
Many "library" - it is a problem for me, one "library" - is not! :)))

**Comment by Meychi** [comment]
This list can be managed from ProjectManager settings -> Filtered Directory Names. If you want to improve this, please modify the current logic in ClasspathNode.

**Pull request closed without merging**
