### PR TITLE
Clear current member at the final } if it's a method

### PR DESCRIPTION
**Pull request by Neverbirth**
This fixes methods setting some compiler metadata as its type if the meta has arguments and they are not fully written yet.

Fixes issue #372 (last Gama11's comment). EDIT: Fixed only after a function with no type. If it's a var it's not working right yet.

### CODE REVIEW

**Comment by Neverbirth** [comment]
Please, @Gama11 could you try out this? because after making the change I've seen that even without the changed code I cannot reproduce the case...

**Comment by Neverbirth** [comment]
I close it until I get a reproducible case...

**Comment by Gama11** [comment]
This doesn't fix the issue for me.

**Comment by Neverbirth** [comment]
Just checked, it fixes it if the previous member to the wrong meta is a function, but not a var.

**Comment by Neverbirth** [comment]
It seems that fixing the var case is not so trivial, if I clear the current member after the end of the var declaration there is some strange behavior in a case. I'll have to dedicate more time to that one

**Pull request merged**
