### PR TITLE
fixes: Displays the status of files under version control system

### PR DESCRIPTION
**Pull request by SlavaRa**
Before fix:

After:

### CODE REVIEW

**Comment by elsassph** [comment]
I'm sorry to repeat it, but can you keep code cleanup and fixes in separated PRs please?

**Comment by SlavaRa** [comment]
Ok

**Comment by elsassph** [comment]
I essentially don't agree with most of the stylistic changes you did: 

- I like whitespace; blank lines are here for code respiration,
- I like to move `return` on the next line as it makes it more "visible" in the code,
- I don't add `private` like in Haxe because that's the default http://stackoverflow.com/questions/3763612/default-visibility-for-c-sharp-classes-and-members-fields-methods-etc.

I'm ok with cleaning up `using` statements, fixing inconsistent whitespace, removing dead code, fixing incorrect `public` visibility.

**Comment by Neverbirth** [comment]
I like adding the modifier, first, it makes clear the developer intention and second, it's clearer and faster for people reading the code, as the link shows, the default visibility varies (even between .NET languages, for example the default in these cases would be internal or public in other .NET languages).

**Pull request closed without merging**
