### PR TITLE
Sci.IsVScrollBar and IsHScrollBar defer to active scrollbar

### PR DESCRIPTION
**Pull request by JoeRobich**
When custom scrollbars are in use then IsVScrollBar and IsHScrollBar should get/set their visibility instead of the native scrollbar visibility. 

- Separate properties for custom/native scrollbar visibility are added.
- The IsVScrollBar/IsHScrollBar defer to the active scrollbar's visibility property.
- Scrollbar visibility is synced when custom scrollbars are added or removed.
- OnResize doesn't include custom scrollbar size when their visibility is set to false.

### CODE REVIEW

**Comment by Meychi** [comment]
I just started thinking this yesterday. :) With this implementation we would need to expose and sync multiple properties between split sci controls. I'll try to come up with a simpler approach.

**Comment by Meychi** [comment]
Ok, i did my implementation and based on my tests it works correctly, comments?

https://github.com/fdorg/flashdevelop/commit/e5bce38e42fa686727b80a7c4423f58e92bdc0c9

**Comment by JoeRobich** [comment]
My only thought is that Resize needs to be called anytime the custom scrollbar's visibility changes.

**Comment by Meychi** [comment]
Ok, i will address and test that.

**Comment by Meychi** [comment]
Should be good now. Other comments or ideas?

**Comment by JoeRobich** [comment]
No. I think that will work great. Thanks!

**Pull request closed without merging**
