### PR TITLE
Fixes issue #1431

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Neverbirth @elsassph @Meychi please review this PR

**Comment by Neverbirth** [comment]
I think it's OK, but have to check against some local changes when I have time.

**Comment by SlavaRa** [comment]
Thanks)

**Comment by SlavaRa** [comment]
@Neverbirth what about this PR?

**Comment by Neverbirth** [comment]
Didn't check yet. Will try during this week.

**Comment by elsassph** [comment]
Looks good.

**Comment by andrew-git** [comment]
Everything working, such much needed.
Could it be approved?

**Comment by Neverbirth** [comment]
IMHO "much needed" seems overestimating it as creating classes with the same name as a parent class is uncommon and I think it should be avoided as much as possible except for extreme cases heh.

I will finish with this during this week.

**Comment by SlavaRa** [comment]
@andrew-git , sorry

**Comment by Meychi** [comment]
@Neverbirth, ok for merge?

**Comment by SlavaRa** [comment]
bump

**Pull request merged**
