### PR TITLE
Better events generator when using Haxe not for Flash. 

### PR DESCRIPTION
**Pull request by elsassph**
eg. DOM addEventListener shouldn't import flash.events.Event or even suggest to generate a DataEvent handler.

### CODE REVIEW

**Comment by Neverbirth** [comment]
Unit tests, please :P.

**Comment by elsassph** [comment]
Headshot.

**Comment by Meychi** [comment]
@Neverbirth, @elsassph: Can this be merged?

**Comment by elsassph** [comment]
There are a few tests I think that's cool.

**Pull request merged**
