### PR TITLE
[Haxe] Parse `-lib` and `-cp` after `-next`. fixes issue #1154

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by Neverbirth** [comment]
I think there were some reasons against this. @elsassph ?

**Comment by SlavaRa** [comment]
My working project consists of a single file .hxml, for several targets.
Running the specific target occurs via gradle.
I have a special platform for such projects(Settings\Platforms\Haxe\).
But I can not work comfortably due to this issue. So I have a separate FD project for each platform and i have to switch between them

**Comment by elsassph** [comment]
The rationale was that it could cause problems because conflicting libs/cps could cause compiler errors during completion if your different compilations target different platforms.

This limitation was meant to be lifted by allowing the user to choose one of the targets of the hxml when multiple are available.

**Comment by Neverbirth** [comment]
Oh, yeah. Right.

So I would prefer to see [this feature request](https://github.com/fdorg/flashdevelop/issues/455) implemented rather than this. In fact, it's on my todo, but I would be glad if someone is able to look into it before heh.

**Pull request closed without merging**
