### PR TITLE
Fixes issue #1436

### PR DESCRIPTION
**Pull request by SlavaRa**
This PR requires Haxe on CI.

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Neverbirth please review this PR

**Comment by Neverbirth** [comment]
Conflicts.

Also, would be nice to add some custom attribute to tests needing Haxe installed, even if it does nothing, for easier spotting them and further analyzing.

I see this does more than addressing that issue, but I think it's OK. I still have to check some stuff.

**Comment by SlavaRa** [comment]
I will fix conflicts today or weekend.

**Comment by SlavaRa** [comment]
>> Also, would be nice to add some custom attribute to tests needing Haxe installed, even if it does nothing, for easier spotting them and further analyzing.

A good idea. I think this can be done

**Pull request merged**
