### PR TITLE
Fixed fails after renaming when renaming function parameters in some cases. Part2

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Neverbirth please review this PR

**Comment by SlavaRa** [comment]
this PR fixes some bugs of the previous part

**Comment by Neverbirth** [comment]
I'll do my best to review  this ASAP, but I'm not sure I'll be able to do so today.

**Comment by SlavaRa** [comment]
ok. thanks)

**Comment by SlavaRa** [comment]
WIP

**Pull request closed without merging**
