### PR TITLE
Make IBatchProcessor removable

### PR DESCRIPTION
**Pull request by chipshort**
@Neverbirth Regarding #1510

### CODE REVIEW

**Comment by Neverbirth** [comment]
@SlavaRa ? For me it looks like EventManager is not needed and I would go with just a normal class exposed by the CodeRefactor plugin and normal events. But you decide.

**Comment by SlavaRa** [comment]
Please give me 30 minutes to study the code :)

**Comment by SlavaRa** [comment]
I, too, do not see the point in these events, but maybe the @chipshort will tell we why they are needed?

**Comment by chipshort** [comment]
@SlavaRa Well, I added the events because @Neverbirth asked for them.

**Comment by Neverbirth** [comment]
Yeah, I think having events is useful as there may be the need to refresh information when processors are added or removed.

**Pull request merged**
