### PR TITLE
Notify Restart Required on Settings Change

### PR DESCRIPTION
**Pull request by wise0704**
I think it's good to let users know which settings take effect only after a restart. 
Really simple syntax for developers: just add a `[RequiresRestart]` attribute.

### CODE REVIEW

**Comment by wise0704** [comment]
One minor problem with this is that, when you install something with AppMan and it calls `RestartRequired()`, opening and closing the settings dialog will hide the `restartButton`. But this is really minor. They can always click File > Restart.

**Comment by Meychi** [comment]
Has conflicts now.

I think its better just to just request restart and not cancel it if settings are restored.

**Comment by wise0704** [comment]
Are you sure? I thought that would be annoying...

**Comment by wise0704** [comment]
Well, I guess it shouldn't be canceled if the dialog was closed then reopened, then the value was restored. 
So remove this: https://github.com/fdorg/flashdevelop/pull/1261/files#diff-90b75daa5189dd008a8d9c44e85a41e2R599 and do some checks to see if the required flag was already set.

**Comment by wise0704** [comment]
@Meychi Can you review please?

**Comment by wise0704** [comment]
Which other settings require restart on modification?

**Comment by Neverbirth** [comment]
I'm OK with this one.

**Pull request merged**
