### PR TITLE
Better Tools->Program Settings... icon, closes #700

### LINKED ISSUE #700: Better Tools->Program Settings... icon
The current icon is extremely generic and thus not very helpful - typically a wrench or a gear is used for settings.

### PR DESCRIPTION
**Pull request by Gama11**
Now:

Before:

### CODE REVIEW

**Comment by Meychi** [comment]
Wrong way around :)

**Comment by Gama11** [comment]
What do you mean?

**Comment by Meychi** [comment]
Nothing, read wrong and deleted comment in a sec. :)

**Comment by Gama11** [comment]
Ah. :) The comment didn't disappear for me because I still had this issue open in a tab.

**Pull request merged**
