### PR TITLE
[distro_haxedevelop] added Docs folder with release notes

### PR DESCRIPTION
**Pull request by markknol**
Added docs.

image

### CODE REVIEW

**Comment by SlavaRa** [comment]
You should replace "Microsoft.NET 2.0" by "Microsoft.NET 3.5"

**Comment by markknol** [comment]
Done :+1:  You should do the same in the original doc :smile:

**Comment by Meychi** [comment]
distro_haxedevelop has been already merged to development branch. :) Please do the PR there.

**Comment by markknol** [comment]
This is a separate branch?

**Comment by markknol** [comment]
I don't know how..

**Comment by Gama11** [comment]
You can't change the target branch of a PR, you have to close it and open a new one.

**Comment by Meychi** [comment]
Done.

**Pull request closed without merging**
